# Generated by Django 3.1.5 on 2021-02-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receipt_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='created_at',
            new_name='date',
        ),
    ]
