# Generated by Django 3.1.5 on 2021-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='date',
            new_name='created_at',
        ),
    ]
