export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_RECEIPTS = 'GET_RECEIPTS';
export const ADD_RECEIPT = 'ADD_RECEIPT';

export const GET_FRIENDS = 'GET_FRIENDS';
export const SEARCH_USER = 'SEARCH_USER';
export const SEND_REQUEST = 'SEND_REQUEST';
export const GET_REQUESTS = 'GET_REQUESTS';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const GET_BALANCE = 'GET_BALANCE';
export const RESET_BALANCE = 'RESET_BALANCE';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const RETURN_ALERT = 'RETURN_ALERT';
